# Generated by Django 6.0.5 on 2026-05-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_experiences', models.IntegerField(verbose_name="Nombre d'experiences")),
                ('frequence', models.FloatField(verbose_name='Frequence de succes')),
                ('date_simulation', models.DateTimeField(auto_now_add=True, verbose_name='Date de simulation')),
            ],
            options={
                'verbose_name': 'Resultat de simulation',
                'verbose_name_plural': 'Resultats de simulations',
                'ordering': ['-date_simulation'],
            },
        ),
    ]
